default: &default
 adapter: postgresql

development:
 <<: *default
 database: gcamp_development

test:
 <<: *default
 database: gcamp_test

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres
